/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aels;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class CourseModule extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseModule.class.getName());

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public CourseModule() {
        conn=Dbc.connectDB();
        initComponents();
        table();
    }
    public final void table(){
      try {
        String sql = "SELECT * FROM coursename ";
        pst = conn.prepareStatement(sql); // use prepareStatement instead of prepareCall
        rs = pst.executeQuery();
        coursetb.setModel(DbUtils.resultSetToTableModel(rs));

        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Coursemodule = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetb = new javax.swing.JTable();
        Coursesearchtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        coursenametf = new javax.swing.JTextField();
        addCourseb = new javax.swing.JButton();
        removeCourseb = new javax.swing.JButton();
        updateCourseb = new javax.swing.JButton();
        backAdminb = new javax.swing.JButton();
        coursecodejl = new javax.swing.JLabel();
        coursecodetf = new javax.swing.JTextField();
        courseSearchb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Coursemodule.setBackground(new java.awt.Color(0, 255, 204));
        Coursemodule.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Adaptive E-Learning System");

        coursetb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        coursetb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursetbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(coursetb);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Course Name:");

        addCourseb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addCourseb.setText("Add");
        addCourseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoursebActionPerformed(evt);
            }
        });

        removeCourseb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removeCourseb.setText("Remove");
        removeCourseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCoursebActionPerformed(evt);
            }
        });

        updateCourseb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateCourseb.setText("Update");
        updateCourseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCoursebActionPerformed(evt);
            }
        });

        backAdminb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backAdminb.setText("Back");
        backAdminb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAdminbActionPerformed(evt);
            }
        });

        coursecodejl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        coursecodejl.setText("Course Code:");

        courseSearchb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        courseSearchb.setText("Search");
        courseSearchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseSearchbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoursemoduleLayout = new javax.swing.GroupLayout(Coursemodule);
        Coursemodule.setLayout(CoursemoduleLayout);
        CoursemoduleLayout.setHorizontalGroup(
            CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CoursemoduleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(136, 136, 136))
            .addGroup(CoursemoduleLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursemoduleLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(coursecodejl)
                            .addComponent(courseSearchb))
                        .addGap(23, 23, 23)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Coursesearchtf)
                            .addComponent(coursenametf)
                            .addComponent(coursecodetf, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(CoursemoduleLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateCourseb)
                            .addComponent(addCourseb))
                        .addGap(42, 42, 42)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backAdminb)
                            .addComponent(removeCourseb))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        CoursemoduleLayout.setVerticalGroup(
            CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursemoduleLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursemoduleLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(CoursemoduleLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Coursesearchtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(courseSearchb))
                        .addGap(27, 27, 27)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(coursenametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coursecodejl)
                            .addComponent(coursecodetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCourseb)
                            .addComponent(removeCourseb))
                        .addGap(18, 18, 18)
                        .addGroup(CoursemoduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateCourseb)
                            .addComponent(backAdminb))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Coursemodule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Coursemodule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateCoursebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCoursebActionPerformed
        // TODO add your handling code here:
         try {
      
        String sql = "UPDATE coursename SET course_name=?, course_code=? WHERE course_name=?";

        pst = conn.prepareStatement(sql);
        pst.setString(1,coursecodetf.getText());   
        pst.setString(2,coursenametf.getText()); 
      

        int rowsUpdated = pst.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "course updated successfully!");
            table(); // refresh the table
            clearFields(); // optional: reset input fields
        } else {
            JOptionPane.showMessageDialog(null, " No course found with that coursename!");
        }

        pst.close();

        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_updateCoursebActionPerformed

    private void addCoursebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoursebActionPerformed
        // TODO add your handling code here:
        try {
        // Basic validation
        if (coursenametf.getText().trim().isEmpty() ||
            coursecodetf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course name and Course code cannot be empty!");
            return;
        }

        String sql = "INSERT INTO coursename (course_name, course_code) VALUES (?, ?)";

        pst = conn.prepareStatement(sql);
        pst.setString(1, coursenametf.getText().trim());
        pst.setString(2, coursecodetf.getText().trim());

        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Course added successfully!");
            table();       // refresh table
            clearFields(); // clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add Course!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_addCoursebActionPerformed

    private void coursetbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursetbMouseClicked
        // TODO add your handling code here:
         DefaultTableModel tmodel = (DefaultTableModel)coursetb.getModel();
        int selectrowintex = coursetb.getSelectedRow();
       coursenametf.setText(tmodel.getValueAt(selectrowintex, 1).toString());
        coursecodetf.setText(tmodel.getValueAt(selectrowintex, 2).toString());
    }//GEN-LAST:event_coursetbMouseClicked

    private void courseSearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseSearchbActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Select * from coursename where course_name =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,Coursesearchtf.getText());
            rs = pst.executeQuery();
            if(rs.next()){
             
                coursenametf.setText(rs.getString("username"));
              coursecodetf.setText(rs.getString("password"));
              
            }else{
                JOptionPane.showMessageDialog(null," No result found");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
}
    }//GEN-LAST:event_courseSearchbActionPerformed

    private void removeCoursebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCoursebActionPerformed
        // TODO add your handling code here:
         try {
        String sql = "DELETE FROM coursename WHERE username=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Coursesearchtf.getText());
        int rows = pst.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Student deleted successfully!");
            table();
        } else {
            JOptionPane.showMessageDialog(null, "No Student found with that username!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_removeCoursebActionPerformed

    private void backAdminbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAdminbActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        AdminPage a1 =new AdminPage();
        a1.setVisible(true);
    }//GEN-LAST:event_backAdminbActionPerformed
     public void clearFields(){
         Coursesearchtf.setText("");
         coursenametf.setText("");
    // usernametf.setText("");  // duplicate
    coursecodetf.setText("");     // <-- this is what you probably mean
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseModule().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Coursemodule;
    private javax.swing.JTextField Coursesearchtf;
    private javax.swing.JButton addCourseb;
    private javax.swing.JButton backAdminb;
    private javax.swing.JButton courseSearchb;
    private javax.swing.JLabel coursecodejl;
    private javax.swing.JTextField coursecodetf;
    private javax.swing.JTextField coursenametf;
    private javax.swing.JTable coursetb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeCourseb;
    private javax.swing.JButton updateCourseb;
    // End of variables declaration//GEN-END:variables
}
