/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.aels;

/**
 *
 * @author MD SADRUL ANAM
 */
public class HomePage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /** Creates new form HomePage */
    public HomePage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Homepagesp = new javax.swing.JPanel();
        aelsjl = new javax.swing.JLabel();
        whatjl = new javax.swing.JLabel();
        studentb = new javax.swing.JButton();
        teacherb = new javax.swing.JButton();
        adminb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Homepagesp.setBackground(new java.awt.Color(0, 255, 255));

        aelsjl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        aelsjl.setText("Adaptive E-Learning System");

        whatjl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        whatjl.setText("What is your role in adaptive E-Learning System");

        studentb.setText("Student");
        studentb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbActionPerformed(evt);
            }
        });

        teacherb.setText("Teacher");

        adminb.setText("Admin");

        javax.swing.GroupLayout HomepagespLayout = new javax.swing.GroupLayout(Homepagesp);
        Homepagesp.setLayout(HomepagespLayout);
        HomepagespLayout.setHorizontalGroup(
            HomepagespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepagespLayout.createSequentialGroup()
                .addGroup(HomepagespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomepagespLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(aelsjl, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomepagespLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(whatjl))
                    .addGroup(HomepagespLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(studentb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminb)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        HomepagespLayout.setVerticalGroup(
            HomepagespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomepagespLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(aelsjl)
                .addGap(39, 39, 39)
                .addComponent(whatjl)
                .addGap(46, 46, 46)
                .addGroup(HomepagespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentb)
                    .addComponent(teacherb)
                    .addComponent(adminb))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepagesp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Homepagesp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Homepagesp;
    private javax.swing.JButton adminb;
    private javax.swing.JLabel aelsjl;
    private javax.swing.JButton studentb;
    private javax.swing.JButton teacherb;
    private javax.swing.JLabel whatjl;
    // End of variables declaration//GEN-END:variables

}
