
package com.mycompany.aels;

/**
 *
 * @author MD SADRUL ANAM
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sequizb = new javax.swing.JButton();
        progquizb = new javax.swing.JButton();
        dsaquizb = new javax.swing.JButton();
        dmgquizb = new javax.swing.JButton();
        mathquizb = new javax.swing.JButton();
        backb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Adaptive E-Learning System");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Select a Course for Quiz");

        sequizb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sequizb.setText("SE");
        sequizb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sequizbActionPerformed(evt);
            }
        });

        progquizb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        progquizb.setText("PROG");
        progquizb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progquizbActionPerformed(evt);
            }
        });

        dsaquizb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dsaquizb.setText("DSA");
        dsaquizb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dsaquizbActionPerformed(evt);
            }
        });

        dmgquizb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dmgquizb.setText("DMG");
        dmgquizb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmgquizbActionPerformed(evt);
            }
        });

        mathquizb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mathquizb.setText("MATH");
        mathquizb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathquizbActionPerformed(evt);
            }
        });

        backb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backb.setText("Back");
        backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sequizb)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(progquizb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(dsaquizb)
                                .addGap(68, 68, 68)
                                .addComponent(dmgquizb)
                                .addGap(58, 58, 58)
                                .addComponent(mathquizb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backb)
                                .addGap(36, 36, 36)))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backb)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sequizb)
                    .addComponent(progquizb)
                    .addComponent(dsaquizb)
                    .addComponent(dmgquizb)
                    .addComponent(mathquizb))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        StudentPage stp1=new StudentPage();
        stp1.setVisible(true);
    }//GEN-LAST:event_backbActionPerformed

    private void sequizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sequizbActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // hide this window
    QuizQuestionPage qp = new QuizQuestionPage("SE");
            qp.setVisible(true);
    }//GEN-LAST:event_sequizbActionPerformed

    private void progquizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progquizbActionPerformed
        // TODO add your handling code here:
         this.setVisible(false); // hide this window
    QuizQuestionPage qp = new QuizQuestionPage("PROG");
            qp.setVisible(true);
    }//GEN-LAST:event_progquizbActionPerformed

    private void dsaquizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dsaquizbActionPerformed
        // TODO add your handling code here:
         this.setVisible(false); // hide this window
    QuizQuestionPage qp = new QuizQuestionPage("DSA");
            qp.setVisible(true);
    }//GEN-LAST:event_dsaquizbActionPerformed

    private void dmgquizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmgquizbActionPerformed
        // TODO add your handling code here:
         this.setVisible(false); // hide this window
    QuizQuestionPage qp = new QuizQuestionPage("DMG");
            qp.setVisible(true);
    }//GEN-LAST:event_dmgquizbActionPerformed

    private void mathquizbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathquizbActionPerformed
        // TODO add your handling code here:
         this.setVisible(false); // hide this window
    QuizQuestionPage qp = new QuizQuestionPage("MATH");
            qp.setVisible(true);
    }//GEN-LAST:event_mathquizbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backb;
    private javax.swing.JButton dmgquizb;
    private javax.swing.JButton dsaquizb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mathquizb;
    private javax.swing.JButton progquizb;
    private javax.swing.JButton sequizb;
    // End of variables declaration//GEN-END:variables
}
