/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MD SADRUL ANAM
 */
public class StudentModule extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentModule.class.getName());
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    
    public StudentModule() {
        conn=Dbc.connectDB();
        initComponents();
        table();
    }
    public final void table(){
      try {
        String sql = "SELECT * FROM info WHERE role = 'Student'";
        pst = conn.prepareStatement(sql); // use prepareStatement instead of prepareCall
        rs = pst.executeQuery();
        Studentt.setModel(DbUtils.resultSetToTableModel(rs));

        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernmaejl = new javax.swing.JLabel();
        passwordjl = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        rolejl = new javax.swing.JLabel();
        passwordtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Studentt = new javax.swing.JTable();
        addb = new javax.swing.JButton();
        removeb = new javax.swing.JButton();
        searchtf = new javax.swing.JTextField();
        rolecb = new javax.swing.JComboBox<>();
        updateb = new javax.swing.JButton();
        searchb = new javax.swing.JButton();
        backb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Adaptive E-learning System");

        usernmaejl.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        usernmaejl.setText("username:");

        passwordjl.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        passwordjl.setText("password:");

        rolejl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rolejl.setText("role:");

        passwordtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtfActionPerformed(evt);
            }
        });

        Studentt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        Studentt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudenttMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Studentt);

        addb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addb.setText("Add");
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        removeb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removeb.setText("Remove");
        removeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebActionPerformed(evt);
            }
        });

        rolecb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rolecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student" }));
        rolecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecbActionPerformed(evt);
            }
        });

        updateb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateb.setText("Update");
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        searchb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        searchb.setText("Search");
        searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbActionPerformed(evt);
            }
        });

        backb.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backb.setText("Back");
        backb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(usernmaejl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordjl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rolejl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchb)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernametf)
                            .addComponent(passwordtf)
                            .addComponent(searchtf, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(rolecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(506, 506, 506)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateb)
                                    .addComponent(addb))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeb)
                                    .addComponent(backb))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchb))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernmaejl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjl)
                            .addComponent(passwordtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolejl)
                            .addComponent(rolecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addb)
                            .addComponent(removeb))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateb)
                            .addComponent(backb))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void passwordtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtfActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        // TODO add your handling code here:
        try {
      
        String sql = "UPDATE info SET password=?, role=? WHERE username=?";

        pst = conn.prepareStatement(sql);
        pst.setString(1, passwordtf.getText());  
        pst.setString(2, (String) rolecb.getSelectedItem()); 
        pst.setString(3,usernametf.getText()); 
      

        int rowsUpdated = pst.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Student updated successfully!");
            table(); // refresh the table
            clearFields(); // optional: reset input fields
        } else {
            JOptionPane.showMessageDialog(null, " No student found with that username!");
        }

        pst.close();

        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_updatebActionPerformed

    private void StudenttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudenttMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel)Studentt.getModel();
        int selectrowintex = Studentt.getSelectedRow();
       usernametf.setText(tmodel.getValueAt(selectrowintex, 1).toString());
        passwordtf.setText(tmodel.getValueAt(selectrowintex, 2).toString());
        
        rolecb.removeAllItems();
       String value = tmodel.getValueAt(selectrowintex, 3).toString();
         rolecb.addItem(value);
        
    }//GEN-LAST:event_StudenttMouseClicked

    private void searchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Select * from info where username =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,searchtf.getText());
            rs = pst.executeQuery();
            if(rs.next()){
             
                usernametf.setText(rs.getString("username"));
              passwordtf.setText(rs.getString("password"));
                rolecb.removeAllItems();
  
                 String value = (String) rs.getString("role");
                 rolecb.addItem(value);
              
            }else{
                JOptionPane.showMessageDialog(null," No result found");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
}
        
    }//GEN-LAST:event_searchbActionPerformed

    private void removebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebActionPerformed
        // TODO add your handling code here:
       int selectedRow = Studentt.getSelectedRow();
    if (selectedRow == -1) {  // no selection
        JOptionPane.showMessageDialog(this, "Please select a student from the table first!");
        return;
    }

    // 2. Get the table model
    DefaultTableModel model = (DefaultTableModel) Studentt.getModel();

    // 3. Read username from the selected row
    //    (You already use column 1 for username in StudenttMouseClicked)
    String username = model.getValueAt(selectedRow, 1).toString();

    // 4. Optional: confirm with the user
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete student: " + username + " ?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return; // user clicked NO
    }

    // 5. Delete from DB using the username from the selected row
    try {
        String sql = "DELETE FROM info WHERE username=?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, username);

        int rows = pst.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Student deleted successfully!");
            table();       // refresh table
            clearFields(); // clear text fields & combo
        } else {
            JOptionPane.showMessageDialog(this, "No student found with that username!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_removebActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        // TODO add your handling code here:
        try {
        // Basic validation
        if (usernametf.getText().trim().isEmpty() ||
            passwordtf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty!");
            return;
        }

        String sql = "INSERT INTO info (username, password, role) VALUES (?, ?, ?)";

        pst = conn.prepareStatement(sql);
        pst.setString(1, usernametf.getText().trim());
        pst.setString(2, passwordtf.getText().trim());
        pst.setString(3, (String) rolecb.getSelectedItem());

        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Student added successfully!");
            table();       // refresh table
            clearFields(); // clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add Student!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_addbActionPerformed

    private void backbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbActionPerformed
        this.setVisible(false);
        AdminPage a1 =new AdminPage();
        a1.setVisible(true);
    }//GEN-LAST:event_backbActionPerformed

    private void rolecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecbActionPerformed
    public void clearFields(){
         searchtf.setText("");
    usernametf.setText("");
    // usernametf.setText("");  // duplicate
    passwordtf.setText("");     // <-- this is what you probably meant
    rolecb.setSelectedIndex(0);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentModule().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Studentt;
    private javax.swing.JButton addb;
    private javax.swing.JButton backb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel passwordjl;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JButton removeb;
    private javax.swing.JComboBox<String> rolecb;
    private javax.swing.JLabel rolejl;
    private javax.swing.JButton searchb;
    private javax.swing.JTextField searchtf;
    private javax.swing.JButton updateb;
    private javax.swing.JTextField usernametf;
    private javax.swing.JLabel usernmaejl;
    // End of variables declaration//GEN-END:variables
}
