/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aels;

import javax.swing.JOptionPane; 
public class StudentPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentPage.class.getName());

   private String enrolledCourse;
    public StudentPage() {
        this(null);   // call the other constructor with null
    }
    public StudentPage(String enrolledCourse) {
        this.enrolledCourse = enrolledCourse;
        initComponents();
        // Optional: you can show the enrolled course in the title
        if (enrolledCourse != null) {
            setTitle("Student Page - Enrolled in: " + enrolledCourse);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewContentb = new javax.swing.JButton();
        viewresultb = new javax.swing.JButton();
        courseenrollb = new javax.swing.JButton();
        takequizb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 250, 253));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Adaptive E-Learning System");

        viewContentb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewContentb.setText("View Content");
        viewContentb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewContentbActionPerformed(evt);
            }
        });

        viewresultb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewresultb.setText("View Result");

        courseenrollb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        courseenrollb.setText("Course Enrollment");
        courseenrollb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseenrollbActionPerformed(evt);
            }
        });

        takequizb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        takequizb.setText("Take Quiz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(viewContentb)
                        .addGap(67, 67, 67)
                        .addComponent(viewresultb)
                        .addGap(68, 68, 68)
                        .addComponent(takequizb))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(courseenrollb)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewresultb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(takequizb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewContentb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(courseenrollb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewContentbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewContentbActionPerformed
        // TODO add your handling code here:
        if (enrolledCourse == null) {
        JOptionPane.showMessageDialog(this,
            "Please enroll in a course first using 'Course Enrollment' button.");
        return;
    }

    // Open Video frame for that specific course
   /* Video v = new Video(enrolledCourse);   // <--- IMPORTANT
    v.setLocationRelativeTo(this);         // center relative to StudentPage
    v.setVisible(true);*/
    }//GEN-LAST:event_viewContentbActionPerformed

    private void courseenrollbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseenrollbActionPerformed
        // TODO add your handling code here:
     //  String selectedCourse = (String) courseNamecb.getSelectedItem();  // e.g. "DSA"

    // Open StudentPage with this course
    //StudentPage sp = new StudentPage(selectedCourse);
    //sp.setLocationRelativeTo(null);
   // sp.setVisible(true);

    // Close the enrollment window
    this.dispose();
    }//GEN-LAST:event_courseenrollbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseenrollb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton takequizb;
    private javax.swing.JButton viewContentb;
    private javax.swing.JButton viewresultb;
    // End of variables declaration//GEN-END:variables
}
