package com.mycompany.aels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class TeacherModule extends javax.swing.JFrame {
 Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    public TeacherModule() {
       conn=Dbc.connectDB();
        initComponents();
        table();
    }
     public final void table(){
      try {
        String sql = "SELECT * FROM info WHERE role = 'Teacher'";
        pst = conn.prepareStatement(sql); // use prepareStatement instead of prepareCall
        rs = pst.executeQuery();
        teachertb.setModel(DbUtils.resultSetToTableModel(rs));

        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        usernmaejlt = new javax.swing.JLabel();
        passwordjlt = new javax.swing.JLabel();
        usernametft = new javax.swing.JTextField();
        rolejlt = new javax.swing.JLabel();
        passwordtft = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        teachertb = new javax.swing.JTable();
        addbt = new javax.swing.JButton();
        removebt = new javax.swing.JButton();
        searchtft = new javax.swing.JTextField();
        rolecbt = new javax.swing.JComboBox<>();
        updatebt = new javax.swing.JButton();
        searchbt = new javax.swing.JButton();
        backbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Adaptive E-learning System");

        usernmaejlt.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        usernmaejlt.setText("username:");

        passwordjlt.setFont(new java.awt.Font("SimSun-ExtG", 1, 12)); // NOI18N
        passwordjlt.setText("password:");

        rolejlt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rolejlt.setText("role:");

        passwordtft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtftActionPerformed(evt);
            }
        });

        teachertb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        teachertb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachertbMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(teachertb);

        addbt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addbt.setText("Add");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        removebt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        removebt.setText("Remove");
        removebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebtActionPerformed(evt);
            }
        });

        rolecbt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rolecbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher" }));
        rolecbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecbtActionPerformed(evt);
            }
        });

        updatebt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updatebt.setText("Update");
        updatebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtActionPerformed(evt);
            }
        });

        searchbt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        searchbt.setText("Search");
        searchbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtActionPerformed(evt);
            }
        });

        backbt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(usernmaejlt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordjlt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(rolejlt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(searchbt)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernametft)
                            .addComponent(passwordtft)
                            .addComponent(searchtft)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(rolecbt, 0, 100, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(506, 506, 506)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updatebt)
                                    .addComponent(addbt))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removebt)
                                    .addComponent(backbt))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchtft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbt))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernametft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernmaejlt))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordjlt)
                            .addComponent(passwordtft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolejlt)
                            .addComponent(rolecbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbt)
                            .addComponent(removebt))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updatebt)
                            .addComponent(backbt))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordtftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtftActionPerformed

    private void teachertbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachertbMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tmodel = (DefaultTableModel)teachertb.getModel();
        int selectrowintex = teachertb.getSelectedRow();
        usernametft.setText(tmodel.getValueAt(selectrowintex, 1).toString());
        passwordtft.setText(tmodel.getValueAt(selectrowintex, 2).toString());

        rolecbt.removeAllItems();
        String value = tmodel.getValueAt(selectrowintex, 3).toString();
        rolecbt.addItem(value);

    }//GEN-LAST:event_teachertbMouseClicked

    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        try {
            // Basic validation
            if (usernametft.getText().trim().isEmpty() ||
                passwordtft.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Username and password cannot be empty!");
                return;
            }

            String sql = "INSERT INTO info (username, password, role) VALUES (?, ?, ?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, usernametft.getText().trim());
            pst.setString(2, passwordtft.getText().trim());
            pst.setString(3, (String) rolecbt.getSelectedItem());

            int rowsInserted = pst.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Teacher added successfully!");
                table();       // refresh table
                clearFields(); // clear input fields
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add Teacher!");
            }

            pst.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_addbtActionPerformed

    private void removebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebtActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM info WHERE username=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, searchtft.getText());
            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(null, "Teacher deleted successfully!");
                table();
            } else {
                JOptionPane.showMessageDialog(null, "No Teacher found with that username!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_removebtActionPerformed

    private void rolecbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolecbtActionPerformed

    private void updatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "UPDATE info SET password=?, role=? WHERE username=?";

            pst = conn.prepareStatement(sql);
            pst.setString(1, passwordtft.getText());
            pst.setString(2, (String) rolecbt.getSelectedItem());
            pst.setString(3,usernametft.getText());

            int rowsUpdated = pst.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Teacher updated successfully!");
                table(); // refresh the table
                clearFields(); // optional: reset input fields
            } else {
                JOptionPane.showMessageDialog(null, " No user found with that username!");
            }

            pst.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatebtActionPerformed

    private void searchbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Select * from info where username =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,searchtft.getText());
            rs = pst.executeQuery();
            if(rs.next()){

                usernametft.setText(rs.getString("username"));
                passwordtft.setText(rs.getString("password"));
                rolecbt.removeAllItems();

                String value = (String) rs.getString("role");
                rolecbt.addItem(value);

            }else{
                JOptionPane.showMessageDialog(null," No result found");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_searchbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        this.setVisible(false);
        AdminPage a1 =new AdminPage();
        a1.setVisible(true);
    }//GEN-LAST:event_backbtActionPerformed
     public void clearFields(){
         searchtft.setText("");
    usernametft.setText("");
    // usernametf.setText("");  // duplicate
    passwordtft.setText("");     // <-- this is what you probably meant
    rolecbt.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Studentt;
    private javax.swing.JTable Studentt1;
    private javax.swing.JTable Studentt2;
    private javax.swing.JButton addb;
    private javax.swing.JButton addb1;
    private javax.swing.JButton addb2;
    private javax.swing.JButton addbt;
    private javax.swing.JButton backb;
    private javax.swing.JButton backb1;
    private javax.swing.JButton backb2;
    private javax.swing.JButton backbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel passwordjl;
    private javax.swing.JLabel passwordjl1;
    private javax.swing.JLabel passwordjlt;
    private javax.swing.JTextField passwordtf;
    private javax.swing.JTextField passwordtf1;
    private javax.swing.JTextField passwordtft;
    private javax.swing.JButton removeb;
    private javax.swing.JButton removeb1;
    private javax.swing.JButton removeb2;
    private javax.swing.JButton removebt;
    private javax.swing.JComboBox<String> rolecb;
    private javax.swing.JComboBox<String> rolecb1;
    private javax.swing.JComboBox<String> rolecbt;
    private javax.swing.JLabel rolejl;
    private javax.swing.JLabel rolejl1;
    private javax.swing.JLabel rolejlt;
    private javax.swing.JButton searchb;
    private javax.swing.JButton searchb1;
    private javax.swing.JButton searchb2;
    private javax.swing.JButton searchbt;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTextField searchtf1;
    private javax.swing.JTextField searchtf2;
    private javax.swing.JTextField searchtft;
    private javax.swing.JTable teachertb;
    private javax.swing.JButton updateb;
    private javax.swing.JButton updateb1;
    private javax.swing.JButton updateb2;
    private javax.swing.JButton updatebt;
    private javax.swing.JTextField usernametf;
    private javax.swing.JTextField usernametf1;
    private javax.swing.JTextField usernametf2;
    private javax.swing.JTextField usernametft;
    private javax.swing.JLabel usernmaejl;
    private javax.swing.JLabel usernmaejl1;
    private javax.swing.JLabel usernmaejl2;
    private javax.swing.JLabel usernmaejlt;
    // End of variables declaration//GEN-END:variables
}
