/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aels;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class Video extends javax.swing.JFrame {

     Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    public Video() {
       conn=Dbc.connectDB();
        initComponents();
        table();
    }
     public final void table(){
      try {
        String sql = "SELECT * FROM video";
        pst = conn.prepareStatement(sql); // use prepareStatement instead of prepareCall
        rs = pst.executeQuery();
        videot.setModel(DbUtils.resultSetToTableModel(rs));

        rs.close();
        pst.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        videot = new javax.swing.JTable();
        videoSearchb = new javax.swing.JButton();
        videoSearchtf = new javax.swing.JTextField();
        coursenamejl = new javax.swing.JLabel();
        courseNamecb = new javax.swing.JComboBox<>();
        coursecodejl = new javax.swing.JLabel();
        coursecodecb = new javax.swing.JComboBox<>();
        videotitlejl = new javax.swing.JLabel();
        videotitletf = new javax.swing.JTextField();
        videourljl = new javax.swing.JLabel();
        videourltf = new javax.swing.JTextField();
        addvideob = new javax.swing.JButton();
        removevideob = new javax.swing.JButton();
        updatevideov = new javax.swing.JButton();
        backbb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Adaptive E-Learning System");

        videot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        videot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                videotMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(videot);

        videoSearchb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        videoSearchb.setText("Search");
        videoSearchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoSearchbActionPerformed(evt);
            }
        });

        coursenamejl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coursenamejl.setText("Course name:");

        courseNamecb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        courseNamecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROG", "SE", "DSA", "DMG", "MATH" }));

        coursecodejl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coursecodejl.setText("Course code:");

        coursecodecb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coursecodecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROG 111", "SE 117", "DSA 113", "DMG 115", "MATH 209" }));

        videotitlejl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        videotitlejl.setText("Video title:");

        videourljl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        videourljl.setText("Video url:");

        addvideob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addvideob.setText("Add");
        addvideob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addvideobActionPerformed(evt);
            }
        });

        removevideob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        removevideob.setText("Remove");
        removevideob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removevideobActionPerformed(evt);
            }
        });

        updatevideov.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updatevideov.setText("Update");
        updatevideov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatevideovActionPerformed(evt);
            }
        });

        backbb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbb.setText("Back");
        backbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coursecodejl)
                                    .addComponent(coursenamejl)
                                    .addComponent(videotitlejl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(videourljl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courseNamecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(coursecodecb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(videotitletf)
                                    .addComponent(videourltf)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updatevideov)
                                    .addComponent(addvideob))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removevideob)
                                    .addComponent(backbb))
                                .addGap(36, 36, 36))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(videoSearchb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(videoSearchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(videoSearchb)
                            .addComponent(videoSearchtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coursenamejl)
                            .addComponent(courseNamecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coursecodejl)
                            .addComponent(coursecodecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(videotitlejl)
                            .addComponent(videotitletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(videourljl)
                            .addComponent(videourltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addvideob)
                            .addComponent(removevideob))))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatevideov)
                    .addComponent(backbb))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbbActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TeacherPage tp1=new TeacherPage();
        tp1.setVisible(true);
    }//GEN-LAST:event_backbbActionPerformed

    private void updatevideovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatevideovActionPerformed
        // TODO add your handling code here:
           if (selectedVideoTitle == null) {
        JOptionPane.showMessageDialog(this, "Please select a video first!");
        return;
    }

    try {
        String sql = "UPDATE video "
                   + "SET course_name = ?, course_code = ?, video_title = ?, video_url = ? "
                   + "WHERE video_title = ?";

        pst = conn.prepareStatement(sql);
        pst.setString(1, (String) courseNamecb.getSelectedItem());
        pst.setString(2, (String) coursecodecb.getSelectedItem());
        pst.setString(3, videotitletf.getText().trim());
        pst.setString(4, videourltf.getText().trim());
        pst.setString(5, selectedVideoTitle);  // which row to update

        int rowsUpdated = pst.executeUpdate();

        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Video updated successfully!");
            table();
            clearFields();
            selectedVideoTitle = null;
        } else {
            JOptionPane.showMessageDialog(this, "No video found to update!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_updatevideovActionPerformed
    private String selectedVideoTitle = null; 
    private void videotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_videotMouseClicked
        // TODO add your handling code here:
          DefaultTableModel tmodel = (DefaultTableModel) videot.getModel();
    int row = videot.getSelectedRow();

    if (row == -1) return;

    String courseName = tmodel.getValueAt(row, 0).toString();
    String courseCode = tmodel.getValueAt(row, 1).toString();
    String videoTitle = tmodel.getValueAt(row, 2).toString();
    String videoUrl   = tmodel.getValueAt(row, 3).toString();

    // save the original title (for WHERE clause in UPDATE)
    selectedVideoTitle = videoTitle;

    courseNamecb.removeAllItems();
    courseNamecb.addItem(courseName);

    coursecodecb.removeAllItems();
    coursecodecb.addItem(courseCode);

    videotitletf.setText(videoTitle);
    videourltf.setText(videoUrl);
    }//GEN-LAST:event_videotMouseClicked

    private void videoSearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoSearchbActionPerformed
        // TODO add your handling code here:
         try {
        String sql = "SELECT * FROM video WHERE video_title = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, videoSearchtf.getText().trim());
        rs = pst.executeQuery();

        if (rs.next()) {
            courseNamecb.removeAllItems();
            String value = rs.getString("course_name");
            courseNamecb.addItem(value);

            coursecodecb.removeAllItems();
            String value1 = rs.getString("course_code");
            coursecodecb.addItem(value1);

            String vTitle = rs.getString("video_title");
            String vUrl   = rs.getString("video_url");

            videotitletf.setText(vTitle);
            videourltf.setText(vUrl);

            selectedVideoTitle = vTitle; // so UPDATE/DELETE knows which one
        } else {
            JOptionPane.showMessageDialog(null,"No result found");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_videoSearchbActionPerformed

    private void removevideobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removevideobActionPerformed
        // TODO add your handling code here:
        int selectedRow = videot.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a video from the table first!");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) videot.getModel();
    String videoTitle = model.getValueAt(selectedRow, 4).toString(); // column 2 = video_title

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete video: " + videoTitle + " ?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        String sql = "DELETE FROM video WHERE video_title = ?";
        pst = conn.prepareStatement(sql);
        pst.setString(4, videoTitle);

        int rows = pst.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Video deleted successfully!");
            table();
            clearFields();
            selectedVideoTitle = null;
        } else {
            JOptionPane.showMessageDialog(this, "No video found with that title!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_removevideobActionPerformed

    private void addvideobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addvideobActionPerformed
        // TODO add your handling code here:
         try {
        // Basic validation
        if (videotitletf.getText().trim().isEmpty() ||
            videourltf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Video title and video url cannot be empty!");
            return;
        }

        String sql = "INSERT INTO video (course_name, course_code, video_title,video_url) VALUES (?, ?,  ?, ?)";

        pst = conn.prepareStatement(sql);
         pst.setString(1, (String) courseNamecb.getSelectedItem());
         pst.setString(2, (String) coursecodecb.getSelectedItem());
        pst.setString(3, videotitletf.getText().trim());
        pst.setString(4, videourltf.getText().trim());

        int rowsInserted = pst.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Video content added successfully!");
            table();       // refresh table
            clearFields(); // clear input fields
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add content!");
        }

        pst.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_addvideobActionPerformed

     public void clearFields(){
    videoSearchtf.setText("");
    courseNamecb.setSelectedIndex(0);
    coursecodecb.setSelectedIndex(0);
    videotitletf.setText("");
    videourltf.setText("");
    selectedVideoTitle = null;
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Video().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addvideob;
    private javax.swing.JButton backbb;
    private javax.swing.JComboBox<String> courseNamecb;
    private javax.swing.JComboBox<String> coursecodecb;
    private javax.swing.JLabel coursecodejl;
    private javax.swing.JLabel coursenamejl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removevideob;
    private javax.swing.JButton updatevideov;
    private javax.swing.JButton videoSearchb;
    private javax.swing.JTextField videoSearchtf;
    private javax.swing.JTable videot;
    private javax.swing.JLabel videotitlejl;
    private javax.swing.JTextField videotitletf;
    private javax.swing.JLabel videourljl;
    private javax.swing.JTextField videourltf;
    // End of variables declaration//GEN-END:variables
}
